#!/bin/sh
#PBS -l select=10:system=polaris
#PBS -l place=scatter
#PBS -l walltime=01:00:00
#PBS -N process_gene_data
#PBS -q prod
#PBS -A RL-fold
#PBS -k doe
#PBS -o process_data.out
#PBS -e process_data.err


# Change to working directory
cd $PBS_O_WORKDIR

# MPI and OpenMP settings
NNODES=`wc -l < $PBS_NODEFILE`
NRANKS_PER_NODE=1
NDEPTH=64

NTOTRANKS=$(( NNODES * NRANKS_PER_NODE ))
echo "NUM_OF_NODES= ${NNODES} TOTAL_NUM_RANKS= ${NTOTRANKS} RANKS_PER_NODE= ${NRANKS_PER_NODE}"
echo < $PBS_NODEFILE

# This environment should get passed through mpiexec
module load conda/2022-07-19
conda activate gene_transformer


mpiexec \
    -n ${NTOTRANKS} \
    --ppn ${NRANKS_PER_NODE} \
    --depth=${NDEPTH} \
    --cpu-bind depth \
    --hostfile $PBS_NODEFILE \
    run-polaris.sh \
    python -m gene_transformer.cmdline.fasta_to_h5 \
    -f /lus/eagle/projects/CVD-Mol-AI/hippekp/pgfam_30k  \
    -o /lus/eagle/projects/CVD-Mol-AI/hippekp/pgfam_30k_h5/ \
    -n 64 \
    -t /home/hippekp/github/gene_transformer/gene_transformer/tokenizer_files/codon_wordlevel_100vocab.json \
    -b 2048